version: '3.9'
services:
  back:
    build:
      dockerfile: ./back/Dockerfile
      context: .
    ports:
      - "5000:5000"
    networks:
      - users-system

  front:
    build:
      dockerfile: ./front/Dockerfile
      context: .
    ports:
      - "3000:3000"
    networks:
      - users-system

  mongo:
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: database
        MONGO_INITDB_ROOT_PASSWORD: password
      ports:
        - "27017:27017"
      volumes:
        - mongodata
      networks:
        - users-system
      
volumes:
  mongodata:

networks:
  users-system:
